### ISSUE TITLE
Пофиксить __init__

### ISSUE THREAD

**Issue by Nifacy** [K019N/Test-recognizer-for-AuroraOS#4]
[Такое](https://github.com/K019N/Test-recognizer-for-AuroraOS/blob/main/src%2Fapp%2F__init__.py#L2) в `__init__.py` никогда не указывается, это костыльно и непредсказуемо со стороны пользователя.

Хорошо бы было избавиться от такой логики.

**Comment by K019N** [comment]
Да эти файлы пока не работают вообще, временное решение

**Comment by Nifacy** [comment]
#5
